using System.Collections.Generic;
using Robust.Shared.GameStates;
using Robust.Shared.Maths;

namespace Content.Shared._WL.FrozenWorld.Components;

/// <summary>
/// Networked tile mask for client-side FrozenWorld weather rendering.
///
/// This is visual-only data produced from player-built shelter rooms:
/// - tiles inside closed rooms are listed here;
/// - the client world-space precipitation overlay skips those tiles;
/// - outdoor tiles remain visible, so snow can still be seen through windows/doors.
///
/// Gameplay cold, recovery and weather penetration remain server-side in FrozenThermalQuerySystem.
/// </summary>
[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
public sealed partial class FrozenShelterWeatherMaskComponent : Component
{
    /// <summary>
    /// Closed room tiles where world-space precipitation should not be drawn.
    /// Runtime/network state, generated by FrozenShelterRoomSystem.
    /// </summary>
    [AutoNetworkedField, ViewVariables]
    public List<Vector2i> WeatherOccludedTiles = new();

    /// <summary>
    /// Incremented whenever WeatherOccludedTiles is rebuilt. Client overlays use this to refresh local lookup caches.
    /// </summary>
    [AutoNetworkedField, ViewVariables]
    public int Version;
}
