using System;
using Robust.Client.AutoGenerated;
using Content.Shared._WL.FrozenWorld;
using Content.Shared._WL.FrozenWorld.UI;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._WL.FrozenWorld.UI;

[GenerateTypedNameReferences]
public sealed partial class FrozenThermometerWindow : DefaultWindow
{
    // Body part rows are reused between SetState calls to avoid pressuring the GC and
    // re-laying out the panel ~2x per second while the window is open. The pool is
    // sized for the maximum possible body part count (one per FrozenBodyPart enum value);
    // unused rows are simply hidden.
    private const int MaxBodyPartRows = 7;
    private readonly BodyPartRow[] _bodyPartRows = new BodyPartRow[MaxBodyPartRows];
    private Label _emptyBodyPartLabel = default!;

    public event Action? DebugPressed;

    public FrozenThermometerWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("wl-thermometer-title");
        HeaderLabel.Text = Loc.GetString("wl-thermometer-title");
        BodyPartsHeaderLabel.Text = Loc.GetString("wl-thermometer-body-parts-header");
        DebugButton.OnPressed += _ => DebugPressed?.Invoke();

        TemperaturePanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanelAlt,
            FrozenWorldUiTheme.BorderStrong,
            1,
            14,
            14,
            12,
            12);

        ExposurePanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1);

        BodyPartsPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1);

        ExposureBar.BackgroundStyleBoxOverride = FrozenWorldUiTheme.ProgressBackground();
        ExposureBar.ForegroundStyleBoxOverride = FrozenWorldUiTheme.ProgressForeground(FrozenWorldUiTheme.ColdAccent);

        ApplyStaticLabelColors();
        InitializeBodyPartRows();
    }

    private void InitializeBodyPartRows()
    {
        for (var i = 0; i < MaxBodyPartRows; i++)
        {
            // Each row owns its own StyleBoxFlat so we can mutate BorderColor on update
            // without going through FrozenWorldUiTheme.Panel(...) every tick.
            var panelStyle = (StyleBoxFlat)FrozenWorldUiTheme.Panel(
                FrozenWorldUiTheme.SurfacePanelSoft,
                FrozenWorldUiTheme.BorderSoft,
                1,
                10,
                10,
                7,
                7);

            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = panelStyle,
                Margin = new Thickness(0, 0, 0, 5),
                Visible = false,
            };

            var line = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var name = FrozenWorldUiTheme.MakeValueLabel(string.Empty);
            name.SetWidth = 160;

            var rated = FrozenWorldUiTheme.MakeMutedLabel(string.Empty);
            rated.SetWidth = 360;

            var severity = FrozenWorldUiTheme.MakeMutedLabel(string.Empty);
            severity.HorizontalExpand = true;

            line.AddChild(name);
            line.AddChild(rated);
            line.AddChild(severity);
            panel.AddChild(line);

            BodyPartsContainer.AddChild(panel);

            _bodyPartRows[i] = new BodyPartRow(panel, panelStyle, name, rated, severity);
        }

        _emptyBodyPartLabel = FrozenWorldUiTheme.MakeMutedLabel(Loc.GetString("wl-thermometer-body-empty"));
        _emptyBodyPartLabel.Visible = false;
        BodyPartsContainer.AddChild(_emptyBodyPartLabel);
    }

    public void SetState(FrozenThermometerBoundUserInterfaceState state)
    {
        if (!state.Available)
        {
            SetUnavailableState();
            return;
        }

        EnvironmentalTemperatureLabel.Text = Loc.GetString(
            "wl-thermometer-env-temp",
            ("value", FormatSigned(state.EnvironmentalTemperatureCelsius)));

        var stageText = FormatStage(state.Stage);
        var stageColor = FrozenWorldUiTheme.StageColor(state.Stage);

        StageLabel.Text = Loc.GetString("wl-thermometer-stage", ("stage", stageText));
        StageLabel.FontColorOverride = stageColor;

        ExposureLabel.Text = Loc.GetString(
            "wl-thermometer-exposure",
            ("current", state.Exposure.ToString("0.#")),
            ("max", state.MaxExposure.ToString("0.#")));

        var exposureRatio = state.MaxExposure <= 0f
            ? 0f
            : Math.Clamp(state.Exposure / state.MaxExposure, 0f, 1f);

        ExposureBar.Value = exposureRatio;

        if (ExposureBar.ForegroundStyleBoxOverride is StyleBoxFlat foreground)
            foreground.BackgroundColor = stageColor.WithAlpha(0.9f);

        SeverityLabel.Text = Loc.GetString(
            "wl-thermometer-severity",
            ("value", state.TotalColdSeverity.ToString("0.00")));

        WeakestPartLabel.Text = Loc.GetString(
            "wl-thermometer-weakest",
            ("part", FormatBodyPart(state.WeakestBodyPart)),
            ("severity", state.WeakestBodyPartSeverity.ToString("0.00")));

        PopulateBodyParts(state.BodyParts);
    }

    private void PopulateBodyParts(FrozenThermometerBodyPartState[] bodyParts)
    {
        if (bodyParts.Length == 0)
        {
            HideAllBodyPartRows();
            _emptyBodyPartLabel.Visible = true;
            return;
        }

        _emptyBodyPartLabel.Visible = false;

        var count = Math.Min(bodyParts.Length, MaxBodyPartRows);

        for (var i = 0; i < count; i++)
        {
            var part = bodyParts[i];
            var row = _bodyPartRows[i];

            row.Name.Text = FormatBodyPart(part.BodyPart);

            row.Rated.Text = part.IsProtected
                ? Loc.GetString("wl-thermometer-body-protected", ("value", FormatSigned(part.RatedTemperatureCelsius)))
                : Loc.GetString("wl-thermometer-body-unprotected");

            var severityColor = GetSeverityColor(part.ColdSeverity);
            row.Severity.Text = Loc.GetString(
                "wl-thermometer-body-severity",
                ("value", part.ColdSeverity.ToString("0.00")));
            row.Severity.FontColorOverride = severityColor;

            row.PanelStyle.BorderColor = severityColor.WithAlpha(0.8f);
            row.Panel.Visible = true;
        }

        for (var i = count; i < MaxBodyPartRows; i++)
            _bodyPartRows[i].Panel.Visible = false;
    }

    private void HideAllBodyPartRows()
    {
        for (var i = 0; i < MaxBodyPartRows; i++)
            _bodyPartRows[i].Panel.Visible = false;
    }

    private void SetUnavailableState()
    {
        EnvironmentalTemperatureLabel.Text = Loc.GetString("wl-thermometer-env-temp-na");

        StageLabel.Text = Loc.GetString("wl-thermometer-stage-na");
        StageLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;

        ExposureLabel.Text = Loc.GetString("wl-thermometer-exposure-na");
        ExposureBar.Value = 0f;
        if (ExposureBar.ForegroundStyleBoxOverride is StyleBoxFlat foreground)
            foreground.BackgroundColor = FrozenWorldUiTheme.TextSecondary.WithAlpha(0.6f);

        SeverityLabel.Text = Loc.GetString("wl-thermometer-severity-na");
        WeakestPartLabel.Text = Loc.GetString("wl-thermometer-weakest-na");

        HideAllBodyPartRows();
        _emptyBodyPartLabel.Visible = true;
    }

    private void ApplyStaticLabelColors()
    {
        HeaderLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        EnvironmentalTemperatureLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;

        StageLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        ExposureLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        SeverityLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        WeakestPartLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;

        BodyPartsHeaderLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
    }

    private static Color GetSeverityColor(float severity)
    {
        return severity switch
        {
            <= 0.01f => FrozenWorldUiTheme.Success,
            < 0.35f => FrozenWorldUiTheme.ColdAccent,
            < 0.65f => FrozenWorldUiTheme.Warning,
            < 0.9f => FrozenWorldUiTheme.Danger,
            _ => FrozenWorldUiTheme.Critical,
        };
    }

    private static string FormatSigned(float value)
    {
        return value >= 0f ? $"+{value:0.#}" : $"{value:0.#}";
    }

    private static string FormatStage(FrozenColdStage stage)
    {
        return stage switch
        {
            FrozenColdStage.None => Loc.GetString("wl-cold-stage-none"),
            FrozenColdStage.Chilled => Loc.GetString("wl-cold-stage-chilled"),
            FrozenColdStage.Freezing => Loc.GetString("wl-cold-stage-freezing"),
            FrozenColdStage.Hypothermia => Loc.GetString("wl-cold-stage-hypothermia"),
            FrozenColdStage.SevereHypothermia => Loc.GetString("wl-cold-stage-severe-hypothermia"),
            FrozenColdStage.Critical => Loc.GetString("wl-cold-stage-critical"),
            _ => stage.ToString(),
        };
    }

    private static string FormatBodyPart(FrozenBodyPart bodyPart)
    {
        return bodyPart switch
        {
            FrozenBodyPart.Torso => Loc.GetString("wl-body-part-torso"),
            FrozenBodyPart.Arms => Loc.GetString("wl-body-part-arms"),
            FrozenBodyPart.Legs => Loc.GetString("wl-body-part-legs"),
            FrozenBodyPart.Head => Loc.GetString("wl-body-part-head"),
            FrozenBodyPart.Face => Loc.GetString("wl-body-part-face"),
            FrozenBodyPart.Hands => Loc.GetString("wl-body-part-hands"),
            FrozenBodyPart.Feet => Loc.GetString("wl-body-part-feet"),
            _ => bodyPart.ToString(),
        };
    }

    /// <summary>
    /// Cached references to a single body-part row's controls. Created once during
    /// window construction and reused on every <see cref="SetState"/> call.
    /// </summary>
    private sealed record BodyPartRow(
        PanelContainer Panel,
        StyleBoxFlat PanelStyle,
        Label Name,
        Label Rated,
        Label Severity);
}
