using Content.Shared._WL.FrozenWorld.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._WL.FrozenWorld.UI;

[GenerateTypedNameReferences]
public sealed partial class FrozenThermometerWindow : DefaultWindow
{
    public FrozenThermometerWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("wl-thermometer-title");
        HeaderLabel.Text = Loc.GetString("wl-thermometer-title");

        TemperaturePanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanelAlt,
            FrozenWorldUiTheme.BorderStrong,
            1,
            14,
            14,
            12,
            12);

        ApplyStaticLabelColors();
    }

    public void SetState(FrozenThermometerBoundUserInterfaceState state)
    {
        if (!state.Available)
        {
            SetUnavailableState();
            return;
        }

        EnvironmentalTemperatureLabel.Text = Loc.GetString(
            "wl-thermometer-env-temp",
            ("value", FormatSigned(state.EnvironmentalTemperatureCelsius)));
    }

    private void SetUnavailableState()
    {
        EnvironmentalTemperatureLabel.Text = Loc.GetString("wl-thermometer-env-temp-na");
    }

    private void ApplyStaticLabelColors()
    {
        HeaderLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        EnvironmentalTemperatureLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
    }

    private static string FormatSigned(float value)
    {
        return value >= 0f ? $"+{value:0.#}" : $"{value:0.#}";
    }
}
