using System;
using Robust.Client.AutoGenerated;
using Content.Shared._WL.FrozenWorld.UI;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.FrozenWorld.UI;

[GenerateTypedNameReferences]
public sealed partial class FrozenHeatSourceFuelWindow : DefaultWindow
{
    public event Action? OpenStoragePressed;

    public FrozenHeatSourceFuelWindow()
    {
        RobustXamlLoader.Load(this);

        OpenFuelStorageButton.OnPressed += _ => OpenStoragePressed?.Invoke();

        StatusPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanelAlt,
            FrozenWorldUiTheme.BorderStrong,
            1);

        FuelPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1);

        HeatPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1);

        HintPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanelSoft,
            FrozenWorldUiTheme.BorderSoft,
            1,
            10,
            10,
            8,
            8);

        FuelReserveBar.BackgroundStyleBoxOverride = FrozenWorldUiTheme.ProgressBackground();
        FuelReserveBar.ForegroundStyleBoxOverride = FrozenWorldUiTheme.ProgressForeground(FrozenWorldUiTheme.HeatAccent);

        ApplyLabelColors();
    }

    public void SetState(FrozenHeatSourceFuelBoundUserInterfaceState state)
    {
        var status = state.Enabled ? "горит" : "потух";
        var statusColor = state.Enabled ? FrozenWorldUiTheme.Success : FrozenWorldUiTheme.TextMuted;

        StatusLabel.Text = $"Состояние: {status}";
        StatusLabel.FontColorOverride = statusColor;
        ActiveFuelLabel.Text = $"Активное топливо: {FormatPrototype(state.ActiveFuelPrototype)}";

        RemainingLabel.Text = $"Горение: {FormatTime(state.RemainingFuelSeconds)} осталось";
        QueueLabel.Text =
            $"Очередь топлива: {state.FuelItemCount} предмет(ов), {state.FuelStackUnits} ед., запас {FormatTime(state.QueuedFuelSeconds)}";
        LastFuelLabel.Text = $"Последнее топливо: {FormatPrototype(state.LastConsumedFuelPrototype)}";

        HeatLabel.Text = $"Тепло: {FormatSigned(state.EffectiveHeatBonus)}°C  / база {FormatSigned(state.BaseHeatBonus)}°C";
        TransferLabel.Text =
            $"Передача тепла: x{state.EffectiveTransferEfficiency:0.##} / база x{state.BaseTransferEfficiency:0.##}";
        RadiusLabel.Text = $"Радиус: {state.InnerRadius:0.#}–{state.OuterRadius:0.#} м";
        BurnRateLabel.Text =
            $"Скорость горения: x{state.BaseBurnRate * state.ActiveFuelBurnRateMultiplier:0.##} " +
            $"(топливо x{state.ActiveFuelBurnRateMultiplier:0.##}, тепло x{state.ActiveFuelHeatBonusMultiplier:0.##})";

        var totalFuel = MathF.Max(0f, state.RemainingFuelSeconds + state.QueuedFuelSeconds);
        FuelReserveBar.Value = totalFuel <= 0f ? 0f : Math.Clamp(state.RemainingFuelSeconds / totalFuel, 0f, 1f);

        if (FuelReserveBar.ForegroundStyleBoxOverride is StyleBoxFlat foreground)
            foreground.BackgroundColor = state.Enabled
                ? FrozenWorldUiTheme.HeatAccent.WithAlpha(0.88f)
                : FrozenWorldUiTheme.TextMuted.WithAlpha(0.45f);

        if (StatusPanel.PanelOverride is StyleBoxFlat statusPanel)
            statusPanel.BorderColor = state.Enabled ? FrozenWorldUiTheme.HeatAccent : FrozenWorldUiTheme.BorderSoft;
    }

    private void ApplyLabelColors()
    {
        StatusLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        ActiveFuelLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        RemainingLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        QueueLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        LastFuelLabel.FontColorOverride = FrozenWorldUiTheme.TextMuted;
        HeatLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        TransferLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        RadiusLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        BurnRateLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        HintLabel.FontColorOverride = FrozenWorldUiTheme.TextMuted;
    }

    private static string FormatTime(float seconds)
    {
        seconds = MathF.Max(0f, seconds);

        var totalSeconds = (int)MathF.Round(seconds);
        var minutes = totalSeconds / 60;
        var secs = totalSeconds % 60;

        if (minutes <= 0)
            return $"{secs:00}с";

        return $"{minutes:00}:{secs:00}";
    }

    private static string FormatSigned(float value)
    {
        return value >= 0f ? $"+{value:0.#}" : $"{value:0.#}";
    }

    private static string FormatPrototype(string? prototype)
    {
        return string.IsNullOrWhiteSpace(prototype) ? "—" : prototype;
    }
}
