using System;
using Robust.Client.AutoGenerated;
using Content.Shared._WL.FrozenWorld;
using Content.Shared._WL.FrozenWorld.UI;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.FrozenWorld.UI;

[GenerateTypedNameReferences]
public sealed partial class FrozenThermometerWindow : DefaultWindow
{
    public FrozenThermometerWindow()
    {
        RobustXamlLoader.Load(this);

        TemperaturePanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanelAlt,
            FrozenWorldUiTheme.BorderStrong,
            1);

        ExposurePanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1);

        BodyPartsPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1);

        ExposureBar.BackgroundStyleBoxOverride = FrozenWorldUiTheme.ProgressBackground();
        ExposureBar.ForegroundStyleBoxOverride = FrozenWorldUiTheme.ProgressForeground(FrozenWorldUiTheme.ColdAccent);

        ApplyStaticLabelColors();
    }

    public void SetState(FrozenThermometerBoundUserInterfaceState state)
    {
        EnvironmentalTemperatureLabel.Text =
            $"Температура среды: {FormatSigned(state.EnvironmentalTemperatureCelsius)}°C";

        AmbientTemperatureLabel.Text =
            $"Базовая температура зоны: {FormatSigned(state.AmbientTemperatureCelsius)}°C";

        HeatBreakdownLabel.Text =
            $"Тепло: статич. {FormatSigned(state.StaticHeatBonusCelsius)}°C, " +
            $"динамич. {FormatSigned(state.DynamicHeatBonusCelsius)}°C, " +
            $"укрытие {FormatSigned(state.ShelterBonusCelsius)}°C";

        SurfacePenaltyLabel.Text =
            $"Поверхность: штраф к ногам {FormatSigned(state.FootContactPenaltyCelsius)}°C";

        var stageText = FormatStage(state.Stage);
        var stageColor = FrozenWorldUiTheme.StageColor(state.Stage.ToString());

        StageLabel.Text = $"Стадия: {stageText}";
        StageLabel.FontColorOverride = stageColor;

        ExposureLabel.Text =
            $"Переохлаждение: {state.Exposure:0.#} / {state.MaxExposure:0.#}";

        var exposureRatio = state.MaxExposure <= 0f
            ? 0f
            : Math.Clamp(state.Exposure / state.MaxExposure, 0f, 1f);

        ExposureBar.Value = exposureRatio;

        if (ExposureBar.ForegroundStyleBoxOverride is StyleBoxFlat foreground)
            foreground.BackgroundColor = stageColor.WithAlpha(0.9f);

        SeverityLabel.Text =
            $"Опасность холода: {state.TotalColdSeverity:0.00}";

        WeakestPartLabel.Text =
            $"Слабое место: {FormatBodyPart(state.WeakestBodyPart)} ({state.WeakestBodyPartSeverity:0.00})";

        PopulateBodyParts(state.BodyParts);
    }

    private void PopulateBodyParts(FrozenThermometerBodyPartState[] bodyParts)
    {
        BodyPartsContainer.RemoveAllChildren();

        if (bodyParts.Length == 0)
        {
            BodyPartsContainer.AddChild(FrozenWorldUiTheme.MakeMutedLabel("Нет данных по частям тела."));
            return;
        }

        foreach (var part in bodyParts)
        {
            var row = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = FrozenWorldUiTheme.Panel(
                    FrozenWorldUiTheme.SurfacePanelSoft,
                    GetSeverityColor(part.ColdSeverity).WithAlpha(0.8f),
                    1,
                    8,
                    8,
                    6,
                    6),
                Margin = new Thickness(0, 0, 0, 4),
            };

            var line = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var name = FrozenWorldUiTheme.MakeValueLabel(FormatBodyPart(part.BodyPart));
            name.SetWidth = 120;

            var rated = FrozenWorldUiTheme.MakeMutedLabel($"защита до {FormatSigned(part.RatedTemperatureCelsius)}°C");
            rated.SetWidth = 170;

            var severity = FrozenWorldUiTheme.MakeMutedLabel($"холод {part.ColdSeverity:0.00}");
            severity.FontColorOverride = GetSeverityColor(part.ColdSeverity);
            severity.HorizontalExpand = true;

            line.AddChild(name);
            line.AddChild(rated);
            line.AddChild(severity);
            row.AddChild(line);

            BodyPartsContainer.AddChild(row);
        }
    }

    private void ApplyStaticLabelColors()
    {
        EnvironmentalTemperatureLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        AmbientTemperatureLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        HeatBreakdownLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        SurfacePenaltyLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;

        StageLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        ExposureLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        SeverityLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        WeakestPartLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;

        BodyPartsHeaderLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
    }

    private static Color GetSeverityColor(float severity)
    {
        return severity switch
        {
            <= 0.01f => FrozenWorldUiTheme.Success,
            < 0.35f => FrozenWorldUiTheme.ColdAccent,
            < 0.65f => FrozenWorldUiTheme.Warning,
            < 0.9f => FrozenWorldUiTheme.Danger,
            _ => FrozenWorldUiTheme.Critical,
        };
    }

    private static string FormatSigned(float value)
    {
        return value >= 0f ? $"+{value:0.#}" : $"{value:0.#}";
    }

    private static string FormatStage(FrozenColdStage stage)
    {
        return stage switch
        {
            FrozenColdStage.None => "нет",
            FrozenColdStage.Chilled => "озноб",
            FrozenColdStage.Freezing => "замерзание",
            FrozenColdStage.Hypothermia => "переохлаждение",
            FrozenColdStage.SevereHypothermia => "сильное переохлаждение",
            FrozenColdStage.Critical => "критическое состояние",
            _ => stage.ToString(),
        };
    }

    private static string FormatBodyPart(FrozenBodyPart bodyPart)
    {
        return bodyPart switch
        {
            FrozenBodyPart.Torso => "Торс",
            FrozenBodyPart.Arms => "Руки",
            FrozenBodyPart.Legs => "Ноги",
            FrozenBodyPart.Head => "Голова",
            FrozenBodyPart.Face => "Лицо",
            FrozenBodyPart.Hands => "Кисти",
            FrozenBodyPart.Feet => "Ступни",
            _ => bodyPart.ToString(),
        };
    }
}
