using System;
using Robust.Client.AutoGenerated;
using Content.Shared._WL.FrozenWorld.UI;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._WL.FrozenWorld.UI;

[GenerateTypedNameReferences]
public sealed partial class FrozenHeatSourceFuelWindow : DefaultWindow
{
    public event Action? OpenStoragePressed;
    public event Action? ToggleIgnitionPressed;

    public FrozenHeatSourceFuelWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("wl-fuel-window-title");
        OpenFuelStorageButton.Text = Loc.GetString("wl-fuel-window-open-storage");

        OpenFuelStorageButton.OnPressed += _ => OpenStoragePressed?.Invoke();
        ToggleIgnitionButton.OnPressed += _ => ToggleIgnitionPressed?.Invoke();

        StatusPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanelAlt,
            FrozenWorldUiTheme.BorderStrong,
            1);

        HeatPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1,
            14,
            14,
            14,
            14);

        FuelPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1);

        FuelReserveBar.BackgroundStyleBoxOverride = FrozenWorldUiTheme.ProgressBackground();
        FuelReserveBar.ForegroundStyleBoxOverride = FrozenWorldUiTheme.ProgressForeground(FrozenWorldUiTheme.HeatAccent);

        ApplyLabelColors();
    }

    public void SetState(FrozenHeatSourceFuelBoundUserInterfaceState state)
    {
        var statusColor = state.Enabled ? FrozenWorldUiTheme.Success : FrozenWorldUiTheme.TextMuted;

        StatusLabel.Text = Loc.GetString(
            "wl-fuel-window-status",
            ("status", Loc.GetString(GetStatusKey(state))));
        StatusLabel.FontColorOverride = statusColor;

        ToggleIgnitionButton.Text = Loc.GetString(GetToggleIgnitionKey(state));
        ToggleIgnitionButton.Disabled = state.IsIgnited
            ? !state.CanExtinguish
            : !state.CanIgnite;

        HeatLabel.Text = Loc.GetString(
            "wl-fuel-window-heat",
            ("value", FormatSigned(state.EffectiveLocalHeatBonus)));
        HeatLabel.FontColorOverride = state.Enabled
            ? FrozenWorldUiTheme.HeatAccent
            : FrozenWorldUiTheme.TextMuted;

        RemainingLabel.Text = state.Enabled
            ? Loc.GetString("wl-fuel-window-burning", ("time", FormatTime(state.RemainingFuelRealSeconds)))
            : state.HasActiveFuel
                ? Loc.GetString("wl-fuel-window-burning-stopped")
                : Loc.GetString("wl-fuel-window-burning-no-active");

        var totalFuelRealSeconds = MathF.Max(0f, state.RemainingFuelRealSeconds + state.QueuedFuelRealSeconds);
        TotalFuelLabel.Text = totalFuelRealSeconds > 0f
            ? Loc.GetString("wl-fuel-window-total-fuel", ("time", FormatTime(totalFuelRealSeconds)))
            : Loc.GetString("wl-fuel-window-total-fuel-empty");

        QueueLabel.Text = state.HasQueuedFuel
            ? Loc.GetString("wl-fuel-window-queue", ("count", state.FuelStackUnits))
            : Loc.GetString("wl-fuel-window-queue-empty");

        FuelReserveBar.Value = state.ActiveFuelTotalRealSeconds <= 0f
            ? 0f
            : Math.Clamp(state.RemainingFuelRealSeconds / state.ActiveFuelTotalRealSeconds, 0f, 1f);

        if (FuelReserveBar.ForegroundStyleBoxOverride is StyleBoxFlat foreground)
            foreground.BackgroundColor = state.Enabled
                ? FrozenWorldUiTheme.HeatAccent.WithAlpha(0.88f)
                : FrozenWorldUiTheme.TextMuted.WithAlpha(0.45f);

        if (StatusPanel.PanelOverride is StyleBoxFlat statusPanel)
            statusPanel.BorderColor = state.Enabled ? FrozenWorldUiTheme.HeatAccent : FrozenWorldUiTheme.BorderSoft;
    }

    private void ApplyLabelColors()
    {
        StatusLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        HeatLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        RemainingLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        TotalFuelLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        QueueLabel.FontColorOverride = FrozenWorldUiTheme.TextMuted;
    }

    private static string GetToggleIgnitionKey(FrozenHeatSourceFuelBoundUserInterfaceState state)
    {
        if (state.IsIgnited)
            return "wl-fuel-window-extinguish";

        if ((state.HasActiveFuel || state.HasQueuedFuel) && !state.CanIgnite)
            return "wl-fuel-window-needs-ignition";

        return "wl-fuel-window-ignite";
    }

    private static string GetStatusKey(FrozenHeatSourceFuelBoundUserInterfaceState state)
    {
        if (state.Enabled)
            return "wl-fuel-window-status-burning";

        if (state.HasActiveFuel || state.HasQueuedFuel)
            return state.IsIgnited ? "wl-fuel-window-status-igniting" : "wl-fuel-window-status-stopped";

        return "wl-fuel-window-status-no-fuel";
    }

    private static string FormatTime(float seconds)
    {
        seconds = MathF.Max(0f, seconds);

        var totalSeconds = (int)MathF.Round(seconds);
        var hours = totalSeconds / 3600;
        var minutes = totalSeconds / 60 % 60;
        var secs = totalSeconds % 60;

        if (hours > 0)
            return $"{hours:00}:{minutes:00}:{secs:00}";

        return $"{minutes:00}:{secs:00}";
    }

    private static string FormatSigned(float value)
    {
        return value >= 0f ? $"+{value:0.#}" : $"{value:0.#}";
    }
}
