using System;
using Robust.Client.AutoGenerated;
using Content.Shared._WL.FrozenWorld.UI;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.FrozenWorld.UI;

[GenerateTypedNameReferences]
public sealed partial class FrozenHeatSourceFuelWindow : DefaultWindow
{
    public event Action? OpenStoragePressed;
    public event Action? ToggleIgnitionPressed;

    public FrozenHeatSourceFuelWindow()
    {
        RobustXamlLoader.Load(this);

        OpenFuelStorageButton.OnPressed += _ => OpenStoragePressed?.Invoke();
        ToggleIgnitionButton.OnPressed += _ => ToggleIgnitionPressed?.Invoke();

        StatusPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanelAlt,
            FrozenWorldUiTheme.BorderStrong,
            1);

        HeatPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1,
            14,
            14,
            14,
            14);

        FuelPanel.PanelOverride = FrozenWorldUiTheme.Panel(
            FrozenWorldUiTheme.SurfacePanel,
            FrozenWorldUiTheme.Border,
            1);

        FuelReserveBar.BackgroundStyleBoxOverride = FrozenWorldUiTheme.ProgressBackground();
        FuelReserveBar.ForegroundStyleBoxOverride = FrozenWorldUiTheme.ProgressForeground(FrozenWorldUiTheme.HeatAccent);

        ApplyLabelColors();
    }

    public void SetState(FrozenHeatSourceFuelBoundUserInterfaceState state)
    {
        var status = GetStatusText(state);
        var statusColor = state.Enabled ? FrozenWorldUiTheme.Success : FrozenWorldUiTheme.TextMuted;

        StatusLabel.Text = $"Состояние: {status}";
        StatusLabel.FontColorOverride = statusColor;

        ToggleIgnitionButton.Text = GetToggleIgnitionButtonText(state);
        ToggleIgnitionButton.Disabled = state.IsIgnited
            ? !state.CanExtinguish
            : !state.CanIgnite;

        HeatLabel.Text = $"ТЕПЛО: {FormatSigned(state.EffectiveLocalHeatBonus)}°C";
        HeatLabel.FontColorOverride = state.Enabled
            ? FrozenWorldUiTheme.HeatAccent
            : FrozenWorldUiTheme.TextMuted;

        RemainingLabel.Text = state.Enabled
            ? $"Горение: {FormatTime(state.RemainingFuelRealSeconds)} осталось"
            : state.HasActiveFuel
                ? "Горение: остановлено"
                : "Горение: нет активного топлива";

        var totalFuelRealSeconds = MathF.Max(0f, state.RemainingFuelRealSeconds + state.QueuedFuelRealSeconds);
        TotalFuelLabel.Text = totalFuelRealSeconds > 0f
            ? $"Запас топлива: {FormatTime(totalFuelRealSeconds)}"
            : "Запас топлива: нет";

        QueueLabel.Text = state.HasQueuedFuel
            ? $"Топливо в отсеке: {state.FuelStackUnits} ед."
            : "Топливо в отсеке: нет";

        FuelReserveBar.Value = state.ActiveFuelTotalRealSeconds <= 0f
            ? 0f
            : Math.Clamp(state.RemainingFuelRealSeconds / state.ActiveFuelTotalRealSeconds, 0f, 1f);

        if (FuelReserveBar.ForegroundStyleBoxOverride is StyleBoxFlat foreground)
            foreground.BackgroundColor = state.Enabled
                ? FrozenWorldUiTheme.HeatAccent.WithAlpha(0.88f)
                : FrozenWorldUiTheme.TextMuted.WithAlpha(0.45f);

        if (StatusPanel.PanelOverride is StyleBoxFlat statusPanel)
            statusPanel.BorderColor = state.Enabled ? FrozenWorldUiTheme.HeatAccent : FrozenWorldUiTheme.BorderSoft;
    }

    private void ApplyLabelColors()
    {
        StatusLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        HeatLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        RemainingLabel.FontColorOverride = FrozenWorldUiTheme.TextPrimary;
        TotalFuelLabel.FontColorOverride = FrozenWorldUiTheme.TextSecondary;
        QueueLabel.FontColorOverride = FrozenWorldUiTheme.TextMuted;
    }

    private static string GetToggleIgnitionButtonText(FrozenHeatSourceFuelBoundUserInterfaceState state)
    {
        if (state.IsIgnited)
            return "Потушить";

        if ((state.HasActiveFuel || state.HasQueuedFuel) && !state.CanIgnite)
            return "Нужен розжиг";

        return "Разжечь";
    }

    private static string GetStatusText(FrozenHeatSourceFuelBoundUserInterfaceState state)
    {
        if (state.Enabled)
            return "горит";

        if (state.HasActiveFuel || state.HasQueuedFuel)
            return state.IsIgnited ? "запускается" : "не горит";

        return "нет топлива";
    }

    private static string FormatTime(float seconds)
    {
        seconds = MathF.Max(0f, seconds);

        var totalSeconds = (int)MathF.Round(seconds);
        var hours = totalSeconds / 3600;
        var minutes = totalSeconds / 60 % 60;
        var secs = totalSeconds % 60;

        if (hours > 0)
            return $"{hours:00}:{minutes:00}:{secs:00}";

        if (minutes <= 0)
            return $"{secs:00}с";

        return $"{minutes:00}:{secs:00}";
    }

    private static string FormatSigned(float value)
    {
        return value >= 0f ? $"+{value:0.#}" : $"{value:0.#}";
    }
}
