- type: job
  id: WLSettlementHead
  name: job-name-wl-settlement-head
  description: job-description-wl-settlement-head
  setPreference: true
  wlVisibleInLobby: true
  grantPersistentCraftAccess: true
  persistentCraftAllBranches: true
  persistentCraftCanResearch: true
  persistentCraftResearchAllBranches: true
  wlSkillGatherTimeMultiplier: 0.85
  wlSkillGatherYieldMultiplier: 1.35
  wlSkillProcessingYieldMultiplier: 1.25
  wlSkillColdExposureGainMultiplier: 0.8
  wlSkillColdRecoveryMultiplier: 1.15
  wlSkillColdDamageMultiplier: 0.75
  wlSkillMeleeDamageMultiplier: 1.15
  wlSkillMobThresholdBonus: 25
  playTimeTracker: JobWLSettlementHead
  weight: 20
  icon: JobIconHeadOfPersonnel
  startingGear: null # /// WL Change
  canBeAntag: false # /// WL Change
  supervisors: job-supervisors-nobody
  access:
  - Maintenance
  - Service
  - External
  - Engineering
  - Medical
  - Cryogenics # /// WL Change

- type: job
  id: WLMechanic
  name: job-name-wl-mechanic
  description: job-description-wl-mechanic
  setPreference: true
  wlVisibleInLobby: true
  grantPersistentCraftAccess: true
  persistentCraftBranches:
  - WLSettlementHead
  - WLMechanic
  - WLGathererProcessor
  persistentCraftCanResearch: true
  persistentCraftResearchAllBranches: true
  playTimeTracker: JobWLMechanic
  weight: 10
  icon: JobIconStationEngineer
  startingGear: null # /// WL Change
  canBeAntag: false # /// WL Change
  supervisors: job-supervisors-wl-settlement-head
  access:
  - Maintenance
  - Engineering
  - External
  - Cryogenics # /// WL Change

- type: job
  id: WLHunter
  name: job-name-wl-hunter
  description: job-description-wl-hunter
  setPreference: true
  wlVisibleInLobby: true
  grantPersistentCraftAccess: true
  wlSkillColdExposureGainMultiplier: 0.8
  wlSkillColdRecoveryMultiplier: 1.15
  wlSkillColdDamageMultiplier: 0.75
  wlSkillMeleeDamageMultiplier: 1.15
  wlSkillMobThresholdBonus: 25
  playTimeTracker: JobWLHunter
  weight: 10
  icon: JobIconShaftMiner
  startingGear: null # /// WL Change
  canBeAntag: false # /// WL Change
  supervisors: job-supervisors-wl-settlement-head
  access:
  - Maintenance
  - Salvage
  - External
  - Cryogenics # /// WL Change

- type: job
  id: WLGathererProcessor
  name: job-name-wl-gatherer-processor
  description: job-description-wl-gatherer-processor
  setPreference: true
  wlVisibleInLobby: true
  grantPersistentCraftAccess: true
  persistentCraftBranches:
  - WLGathererProcessor
  - WLFieldMedicine
  wlSkillGatherTimeMultiplier: 0.85
  wlSkillGatherYieldMultiplier: 1.35
  wlSkillProcessingYieldMultiplier: 1.25
  playTimeTracker: JobWLGathererProcessor
  weight: 10
  icon: JobIconMedicalDoctor
  startingGear: null # /// WL Change
  canBeAntag: false # /// WL Change
  supervisors: job-supervisors-wl-settlement-head
  access:
  - Maintenance
  - Medical
  - Chemistry
  - Hydroponics
  - Cryogenics # /// WL Change
