using System.Numerics;
using Content.Client._WL.PersistentCrafting;
using Content.Client._WL.PersistentCrafting.UI.Indexes;
using Content.Client._WL.PersistentCrafting.UI.Services;
using Content.Shared._WL.PersistentCrafting;
using Content.Shared.Stacks;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client._WL.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftPlacementWindow : DefaultWindow
{
    private static readonly IReadOnlyList<PersistentCraftRecipePrototype> EmptyRecipes = Array.Empty<PersistentCraftRecipePrototype>();
    private static readonly ISawmill Sawmill = Logger.GetSawmill("persistent-craft.ui.placement");
    private static readonly Color EnoughColor = PersistentCraftUiTheme.Success;
    private static readonly Color MissingColor = PersistentCraftUiTheme.Danger;
    private static readonly Color MutedText = PersistentCraftUiTheme.TextSecondary;

    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private ISharedPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly TagSystem _tag;
    private PersistentCraftClientPrototypeCache? _prototypeCache;
    private PersistentCraftState? _state;
    private PersistentCraftInventorySnapshot _inventorySnapshot = PersistentCraftInventorySnapshot.Empty;
    private PersistentCraftBranchRegistry _branchRegistry;
    private PersistentCraftTextResolver _textResolver;
    private readonly HashSet<string> _reusablePath = new();

    public event Action<string>? OnPlacementPressed;

    public PersistentCraftPlacementWindow()
    {
        IoCManager.InjectDependencies(this);
        _tag = _entityManager.EntitySysManager.GetEntitySystem<TagSystem>();
        _branchRegistry = PersistentCraftBranchRegistry.Create(_prototype);
        _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);

        RobustXamlLoader.Load(this);
        Render();
    }

    public PersistentCraftPlacementWindow(PersistentCraftClientPrototypeCache prototypeCache) : this()
    {
        _prototypeCache = prototypeCache;
        _branchRegistry = prototypeCache.BranchRegistry;
        _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);
        Render();
    }

    public void UpdateState(PersistentCraftState state, PersistentCraftClientPrototypeCache prototypeCache)
    {
        if (!ReferenceEquals(_prototypeCache, prototypeCache))
        {
            _prototypeCache = prototypeCache;
            _branchRegistry = prototypeCache.BranchRegistry;
            _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);
        }

        _state = state;
        Render();
    }

    private void Render()
    {
        RecipeList.RemoveAllChildren();

        if (_state == null || _prototypeCache == null)
        {
            RecipeList.AddChild(CreateMutedLabel(Loc.GetString("persistent-craft-window-loading-points")));
            return;
        }

        if (!_state.Loaded)
        {
            RecipeList.AddChild(CreateMutedLabel(Loc.GetString("persistent-craft-window-loading-points")));
            return;
        }

        var visibleRecipes = GetVisiblePlacementRecipes();
        _inventorySnapshot = BuildInventorySnapshot(visibleRecipes);

        var addedAny = false;
        for (var i = 0; i < _branchRegistry.OrderedBranchIds.Count; i++)
        {
            var branch = _branchRegistry.OrderedBranchIds[i];
            var branchAdded = false;

            for (var recipeIndex = 0; recipeIndex < visibleRecipes.Count; recipeIndex++)
            {
                var recipe = visibleRecipes[recipeIndex];
                if (recipe.Branch != branch)
                    continue;

                if (!branchAdded)
                {
                    RecipeList.AddChild(CreateBranchHeader(branch));
                    branchAdded = true;
                    addedAny = true;
                }

                RecipeList.AddChild(CreatePlacementCard(recipe));
            }
        }

        if (!addedAny)
            RecipeList.AddChild(CreateMutedLabel(Loc.GetString("persistent-craft-placement-window-empty")));
    }

    private List<PersistentCraftRecipePrototype> GetVisiblePlacementRecipes()
    {
        if (_state == null || _prototypeCache == null || !_state.Loaded)
            return new List<PersistentCraftRecipePrototype>();

        var recipes = new List<PersistentCraftRecipePrototype>();
        for (var i = 0; i < _branchRegistry.OrderedBranchIds.Count; i++)
        {
            var branch = _branchRegistry.OrderedBranchIds[i];
            if (!_state.AccessibleBranches.Contains(branch))
                continue;

            var branchRecipes = _prototypeCache.RecipesByBranch.TryGetValue(branch, out var cachedRecipes)
                ? cachedRecipes
                : EmptyRecipes;

            for (var recipeIndex = 0; recipeIndex < branchRecipes.Count; recipeIndex++)
            {
                var recipe = branchRecipes[recipeIndex];
                if (recipe.Placement == null || !HasRequirement(recipe))
                    continue;

                recipes.Add(recipe);
            }
        }

        return recipes;
    }

    private Control CreateBranchHeader(string branch)
    {
        return new Label
        {
            Text = _textResolver.ResolveBranchTitle(branch),
            FontColorOverride = GetBranchAccent(branch),
            Margin = new Thickness(0, 8, 0, 6),
        };
    }

    private Control CreatePlacementCard(PersistentCraftRecipePrototype recipe)
    {
        var accent = GetBranchAccent(recipe.Branch);
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 8),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PersistentCraftUiTheme.SurfacePanel,
                BorderColor = accent.WithAlpha(0.55f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 10,
                ContentMarginBottomOverride = 10,
            },
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 10,
        };

        row.AddChild(CreateRecipeIconPanel(recipe, accent, new Vector2(64, 64)));

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 3,
        };

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
        };

        header.AddChild(new Label
        {
            Text = _textResolver.ResolveRecipeName(recipe),
            FontColorOverride = PersistentCraftUiTheme.TextPrimary,
            HorizontalExpand = true,
            ClipText = true,
        });

        var button = new Button
        {
            Text = Loc.GetString("persistent-craft-placement-action"),
            MinSize = new Vector2(110, 30),
        };
        button.OnPressed += _ => OnPlacementPressed?.Invoke(recipe.ID);
        header.AddChild(button);

        body.AddChild(header);
        body.AddChild(new Label
        {
            Text = _textResolver.BuildRecipeSecondaryLine(recipe),
            FontColorOverride = MutedText,
            ClipText = true,
        });
        body.AddChild(new Label
        {
            Text = Loc.GetString("persistent-craft-placement-requires-node", ("node", GetRequirementText(recipe))),
            FontColorOverride = accent,
            ClipText = true,
        });
        body.AddChild(CreateMaterialsList(recipe));

        row.AddChild(body);
        panel.AddChild(row);
        return panel;
    }

    private Control CreateRecipeIconPanel(PersistentCraftRecipePrototype recipe, Color accent, Vector2 size)
    {
        var panel = new PanelContainer
        {
            MinSize = size,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PersistentCraftUiTheme.SurfaceInset,
                BorderColor = accent.WithAlpha(0.75f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
            },
        };

        panel.AddChild(CreateRecipeIconContent(recipe));
        return panel;
    }

    private Control CreateRecipeIconContent(PersistentCraftRecipePrototype recipe)
    {
        if (TryGetRecipeTexture(recipe, out var texture))
        {
            return new TextureRect
            {
                Texture = texture,
                TextureScale = new Vector2(1.35f, 1.35f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
            };
        }

        return new Label
        {
            Text = PersistentCraftingHelper.GetTierDisplayLabel(recipe.Tier),
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            FontColorOverride = PersistentCraftUiTheme.TextPrimary,
        };
    }

    private Control CreateMaterialsList(PersistentCraftRecipePrototype recipe)
    {
        var list = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 0),
            SeparationOverride = 2,
        };

        list.AddChild(new Label
        {
            Text = Loc.GetString("persistent-craft-placement-materials"),
            FontColorOverride = MutedText,
        });

        if (recipe.Ingredients.Count == 0)
        {
            list.AddChild(CreateMutedLabel(Loc.GetString("persistent-craft-placement-no-materials")));
            return list;
        }

        for (var i = 0; i < recipe.Ingredients.Count; i++)
            list.AddChild(CreateIngredientRow(recipe, recipe.Ingredients[i]));

        return list;
    }

    private Control CreateIngredientRow(PersistentCraftRecipePrototype recipe, PersistentCraftIngredient ingredient)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        row.AddChild(CreateIngredientIcon(ingredient));

        var requiredAmount = GetEffectiveIngredientAmount(recipe, ingredient);
        var text = FormatIngredientRequirement(ingredient, requiredAmount, out var color);
        row.AddChild(new Label
        {
            Text = text,
            FontColorOverride = color,
            HorizontalExpand = true,
            ClipText = true,
        });

        return row;
    }

    private Control CreateIngredientIcon(PersistentCraftIngredient ingredient)
    {
        var panel = new PanelContainer
        {
            MinSize = new Vector2(24, 24),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PersistentCraftUiTheme.SurfaceInset,
                BorderColor = PersistentCraftUiTheme.BorderSoft,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 2,
                ContentMarginRightOverride = 2,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            },
        };

        if (TryGetIngredientTexture(ingredient, out var texture))
        {
            panel.AddChild(new TextureRect
            {
                Texture = texture,
                TextureScale = new Vector2(0.8f, 0.8f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = Control.HAlignment.Center,
                VerticalAlignment = Control.VAlignment.Center,
            });
            return panel;
        }

        panel.AddChild(new Label
        {
            Text = ingredient.GetSelectorKind() == PersistentCraftIngredientSelectorKind.Tag ? "#" : "?",
            FontColorOverride = MutedText,
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
        });
        return panel;
    }

    private Label CreateMutedLabel(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = MutedText,
        };
    }

    private bool HasRequirement(PersistentCraftRecipePrototype recipe)
    {
        return _state != null &&
               _state.AccessibleBranches.Contains(recipe.Branch) &&
               PersistentCraftNodeAvailabilityResolver.HasNodeUnlockedOrAutoAvailable(
                   _state,
                   recipe.RequiredNode,
                   ResolveNodePrototypeOrNull,
                   _reusablePath);
    }

    private string GetRequirementText(PersistentCraftRecipePrototype recipe)
    {
        if (TryResolveRequirementNode(recipe, out var node))
            return _textResolver.ResolveNodeName(node);

        return $"{_textResolver.ResolveBranchTitle(recipe.Branch)} {PersistentCraftingHelper.GetTierDisplayLabel(recipe.Tier)}";
    }

    private string FormatIngredientRequirement(PersistentCraftIngredient ingredient, int requiredAmount, out Color color)
    {
        var name = _textResolver.FormatIngredientName(ingredient);
        if (!IsLocallyVerifiableIngredient(ingredient))
        {
            color = MutedText;
            return $"{name} (?/{requiredAmount})";
        }

        var owned = GetOwnedAmount(ingredient);
        var enough = owned >= requiredAmount;
        color = enough ? EnoughColor : MissingColor;
        return $"{name} ({owned}/{requiredAmount})";
    }

    private bool TryGetRecipeTexture(PersistentCraftRecipePrototype recipe, out Texture? texture)
    {
        texture = null;
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (string.IsNullOrWhiteSpace(displayProto))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(displayProto).Default;
            return texture != null;
        }
        catch (Exception ex)
        {
            Sawmill.Warning($"Failed to resolve placement recipe texture for recipe '{recipe.ID}' using proto '{displayProto}': {ex}");
            texture = null;
            return false;
        }
    }

    private bool TryGetIngredientTexture(PersistentCraftIngredient ingredient, out Texture? texture)
    {
        texture = null;
        var prototypeId = ingredient.GetSelectorKind() switch
        {
            PersistentCraftIngredientSelectorKind.Proto => ingredient.Proto,
            PersistentCraftIngredientSelectorKind.StackType => ResolveStackSpawnPrototype(ingredient.StackType),
            _ => null,
        };

        if (string.IsNullOrWhiteSpace(prototypeId))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(prototypeId).Default;
            return texture != null;
        }
        catch (Exception ex)
        {
            Sawmill.Warning($"Failed to resolve placement ingredient texture for proto '{prototypeId}': {ex}");
            texture = null;
            return false;
        }
    }

    private string? ResolveStackSpawnPrototype(string? stackType)
    {
        if (string.IsNullOrWhiteSpace(stackType) ||
            !_prototype.TryIndex<StackPrototype>(stackType, out var stack))
        {
            return null;
        }

        return stack.Spawn;
    }

    private bool TryResolveRequirementNode(PersistentCraftRecipePrototype recipe, out PersistentCraftNodePrototype node)
    {
        if (_prototypeCache != null &&
            _prototypeCache.TryGetNode(recipe.RequiredNode, out var cachedNode))
        {
            node = cachedNode;
            return true;
        }

        if (_prototype.TryIndex<PersistentCraftNodePrototype>(recipe.RequiredNode, out var resolvedNode))
        {
            node = resolvedNode;
            return true;
        }

        node = default!;
        return false;
    }

    private Color GetBranchAccent(string branch)
    {
        return _branchRegistry.TryGetBranchDefinition(branch, out var definition)
            ? definition.AccentColor
            : Color.White;
    }

    private PersistentCraftNodePrototype? ResolveNodePrototypeOrNull(string nodeId)
    {
        if (_prototypeCache != null &&
            _prototypeCache.TryGetNode(nodeId, out var cachedNode))
        {
            return cachedNode;
        }

        return _prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node)
            ? node
            : null;
    }

    private PersistentCraftInventorySnapshot BuildInventorySnapshot(IReadOnlyList<PersistentCraftRecipePrototype> recipes)
    {
        if (_player.LocalEntity is not { Valid: true } user || !_entityManager.EntityExists(user))
            return PersistentCraftInventorySnapshot.Empty;

        var trackedIngredients = CollectTrackedIngredients(recipes);
        return PersistentCraftInventorySnapshot.Build(
            _entityManager,
            _tag,
            user,
            trackedIngredients);
    }

    private static List<PersistentCraftIngredient> CollectTrackedIngredients(IReadOnlyList<PersistentCraftRecipePrototype> recipes)
    {
        var tracked = new List<PersistentCraftIngredient>();
        var seen = new HashSet<string>();

        for (var i = 0; i < recipes.Count; i++)
        {
            var recipe = recipes[i];
            for (var j = 0; j < recipe.Ingredients.Count; j++)
            {
                var ingredient = recipe.Ingredients[j];
                var key = $"{(int) ingredient.GetSelectorKind()}|{ingredient.GetSelectorValue()}";
                if (seen.Add(key))
                    tracked.Add(ingredient);
            }
        }

        return tracked;
    }

    private static bool IsLocallyVerifiableIngredient(PersistentCraftIngredient ingredient)
    {
        return ingredient.GetSelectorKind() != PersistentCraftIngredientSelectorKind.None &&
               ingredient.GetSelectorKind() != PersistentCraftIngredientSelectorKind.InvalidMultiple;
    }

    private int GetOwnedAmount(PersistentCraftIngredient ingredient)
    {
        return _inventorySnapshot.GetAmount(ingredient);
    }

    private static int GetEffectiveIngredientAmount(PersistentCraftRecipePrototype recipe, PersistentCraftIngredient ingredient)
    {
        return PersistentCraftRecipeRules.GetEffectiveIngredientAmount(recipe, ingredient);
    }
}
