using System.Numerics;
using Content.Client._WL.PersistentCrafting;
using Content.Client._WL.PersistentCrafting.UI.Indexes;
using Content.Client._WL.PersistentCrafting.UI.Services;
using Content.Shared._WL.PersistentCrafting;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WL.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftPlacementWindow : DefaultWindow
{
    private static readonly IReadOnlyList<PersistentCraftRecipePrototype> EmptyRecipes = Array.Empty<PersistentCraftRecipePrototype>();

    [Dependency] private IPrototypeManager _prototype = default!;

    private PersistentCraftClientPrototypeCache? _prototypeCache;
    private PersistentCraftState? _state;
    private PersistentCraftBranchRegistry _branchRegistry;
    private PersistentCraftTextResolver _textResolver;
    private readonly HashSet<string> _reusablePath = new();

    public event Action<string>? OnPlacementPressed;

    public PersistentCraftPlacementWindow()
    {
        IoCManager.InjectDependencies(this);
        _branchRegistry = PersistentCraftBranchRegistry.Create(_prototype);
        _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);

        RobustXamlLoader.Load(this);
        Render();
    }

    public PersistentCraftPlacementWindow(PersistentCraftClientPrototypeCache prototypeCache) : this()
    {
        _prototypeCache = prototypeCache;
        _branchRegistry = prototypeCache.BranchRegistry;
        _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);
        Render();
    }

    public void UpdateState(PersistentCraftState state, PersistentCraftClientPrototypeCache prototypeCache)
    {
        if (!ReferenceEquals(_prototypeCache, prototypeCache))
        {
            _prototypeCache = prototypeCache;
            _branchRegistry = prototypeCache.BranchRegistry;
            _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);
        }

        _state = state;
        Render();
    }

    private void Render()
    {
        RecipeList.RemoveAllChildren();

        if (_state == null || _prototypeCache == null)
        {
            RecipeList.AddChild(CreateMutedLabel(Loc.GetString("persistent-craft-window-loading-points")));
            return;
        }

        if (!_state.Loaded)
        {
            RecipeList.AddChild(CreateMutedLabel(Loc.GetString("persistent-craft-window-loading-points")));
            return;
        }

        var addedAny = false;
        for (var i = 0; i < _branchRegistry.OrderedBranchIds.Count; i++)
        {
            var branch = _branchRegistry.OrderedBranchIds[i];
            if (!_state.AccessibleBranches.Contains(branch))
                continue;

            var recipes = _prototypeCache.RecipesByBranch.TryGetValue(branch, out var branchRecipes)
                ? branchRecipes
                : EmptyRecipes;
            var branchAdded = false;

            for (var recipeIndex = 0; recipeIndex < recipes.Count; recipeIndex++)
            {
                var recipe = recipes[recipeIndex];
                if (recipe.Placement == null || !HasRequirement(recipe))
                    continue;

                if (!branchAdded)
                {
                    RecipeList.AddChild(CreateBranchHeader(branch));
                    branchAdded = true;
                    addedAny = true;
                }

                RecipeList.AddChild(CreatePlacementCard(recipe));
            }
        }

        if (!addedAny)
            RecipeList.AddChild(CreateMutedLabel(Loc.GetString("persistent-craft-placement-window-empty")));
    }

    private Control CreateBranchHeader(string branch)
    {
        var label = new Label
        {
            Text = _textResolver.ResolveBranchTitle(branch),
            FontColorOverride = GetBranchAccent(branch),
            Margin = new Thickness(0, 8, 0, 6),
        };

        return label;
    }

    private Control CreatePlacementCard(PersistentCraftRecipePrototype recipe)
    {
        var accent = GetBranchAccent(recipe.Branch);
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 8),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PersistentCraftUiTheme.SurfacePanel,
                BorderColor = accent.WithAlpha(0.55f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 10,
                ContentMarginBottomOverride = 10,
            },
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        row.AddChild(new Label
        {
            Text = _textResolver.ResolveRecipeName(recipe),
            FontColorOverride = PersistentCraftUiTheme.TextPrimary,
            HorizontalExpand = true,
            ClipText = true,
        });

        var button = new Button
        {
            Text = Loc.GetString("persistent-craft-placement-action"),
            MinSize = new Vector2(110, 30),
        };
        button.OnPressed += _ => OnPlacementPressed?.Invoke(recipe.ID);
        row.AddChild(button);

        body.AddChild(row);
        body.AddChild(new Label
        {
            Text = _textResolver.BuildRecipeSecondaryLine(recipe),
            FontColorOverride = PersistentCraftUiTheme.TextSecondary,
            Margin = new Thickness(0, 4, 0, 0),
            ClipText = true,
        });

        panel.AddChild(body);
        return panel;
    }

    private Label CreateMutedLabel(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = PersistentCraftUiTheme.TextSecondary,
        };
    }

    private bool HasRequirement(PersistentCraftRecipePrototype recipe)
    {
        return _state != null &&
               _state.AccessibleBranches.Contains(recipe.Branch) &&
               PersistentCraftNodeAvailabilityResolver.HasNodeUnlockedOrAutoAvailable(
                   _state,
                   recipe.RequiredNode,
                   ResolveNodePrototypeOrNull,
                   _reusablePath);
    }

    private Color GetBranchAccent(string branch)
    {
        return _branchRegistry.TryGetBranchDefinition(branch, out var definition)
            ? definition.AccentColor
            : Color.White;
    }

    private PersistentCraftNodePrototype? ResolveNodePrototypeOrNull(string nodeId)
    {
        if (_prototypeCache != null &&
            _prototypeCache.TryGetNode(nodeId, out var cachedNode))
        {
            return cachedNode;
        }

        return _prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node)
            ? node
            : null;
    }
}
