using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftRecipeListSummary : Control
{
    private static readonly Color Background = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color Border = PersistentCraftUiTheme.BorderSoft;

    public PersistentCraftRecipeListSummary()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(string text, Color accent)
    {
        RootPanel.PanelOverride = PersistentCraftUiTheme.Panel(
            Background,
            Border,
            1,
            10,
            10,
            8,
            8);

        SummaryLabel.Text = text;
        SummaryLabel.FontColorOverride = accent;
        SummaryLabel.ClipText = true;
    }
}


